Models/Content.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContentManagementSystem.Models
{
    public class Content
    {
        public Guid Id { get; set; }

        public Guid FieldId { get; set; }
        public virtual Field Field { get; set; }

        public Guid ModelId { get; set; }
        public virtual Model Model { get; set; }

        public string Contents { get; set; }
        public int Index { get; set; }

    }
}

Models/ErrorViewModel.cs
using System;

namespace ContentManagementSystem.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Field.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContentManagementSystem.Models
{
    public class Field
    {
        public Guid Id { get; set; }

        public Guid ModelId { get; set; }
        public virtual Model Model { get; set; }

        public string Name { get; set; }
        public FieldType fieldType { get; set; }

        public virtual List<Content> Contents{ get; set;}

    }

    public enum FieldType
    {
        ShortText,
        LongText,
        Number,
        File    
    }
}

Models/Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContentManagementSystem.Models
{
    public class Model
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual IEnumerable<Field> Fields { get; set; }
        public virtual IEnumerable<Content> Contents { get; set; }

    }
}

ViewModels/ModelViewModel.cs
using ContentManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContentManagementSystem.ViewModels
{
    public class ModelViewModel
    {
        public IEnumerable<Model> Models { get; set; }

        public Model ModelToAdd { get; set; }
    }
}

Controllers/FieldsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ContentManagementSystem.Data;
using ContentManagementSystem.Models;
using ContentManagementSystem.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ContentManagementSystem.Controllers
{
    public class FieldsController : Controller
    {
        private readonly ICMSRepository _cmsRepo;
        private readonly IDataRepository _dataRepo;

        public FieldsController(ICMSRepository cmsRepo, IDataRepository dataRepo)
        {
            this._cmsRepo = cmsRepo;
            this._dataRepo = dataRepo;
        }

        public async Task<IActionResult> Index(Guid id)
        {
            var theModel = await _dataRepo.Get<Model>(id);

            var model = new FieldViewModel()
            {
                Fields = await _cmsRepo.GetFieldsForModel(id),
                ModelName = theModel.Name,
                ModelId = id
            };

            //ViewData["ModelId"] = id.ToString();
            return View(model);
        }

        [HttpGet]
        public IActionResult Add(Guid id)
        {
            FieldViewModel model = new FieldViewModel()
            {
                ModelId = id
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(FieldViewModel model)
        {
            if (ModelState.IsValid)
            {   
                var field = new Field()
                {
                    Id = Guid.NewGuid(),
                    ModelId = model.ModelId,
                    Name = model.Name,
                    fieldType = (FieldType)(model.FieldType)
                };

                _dataRepo.Add<Field>(field);

                if (await _dataRepo.SaveAll())
                    return RedirectToAction("Index", new { id = model.ModelId });
            }

            return View(model);
        }


    }
}

Controllers/ModelsController.cs
using ContentManagementSystem.Data;
using ContentManagementSystem.Models;
using ContentManagementSystem.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContentManagementSystem.Controllers
{
    public class ModelsController : Controller
    {
        private readonly IDataRepository _dataRepo;

        public ModelsController(IDataRepository dataRepo)
        {
            this._dataRepo = dataRepo;
        }

        public async Task<IActionResult> Index()
        {
            var model = new ModelViewModel();
            model.Models = await _dataRepo.GetList<Model>();

            return View(model);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(ModelViewModel model)
        {
            if (ModelState.IsValid)
            {
                var modelToAdd = new Model()
                {
                    Name = model.ModelToAdd.Name,
                    Description = model.ModelToAdd.Description
                };

                modelToAdd.Id = Guid.NewGuid();

                _dataRepo.Add<Model>(modelToAdd);

                if(await _dataRepo.SaveAll())
                    return RedirectToAction("Index");

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
            
        } 
    }
}

Views/Models/Add.cshtml
@model Model

<form asp-action="Add"
      method="post">

    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name"/>
    </div>

    <button type="submit"
            class="btn btn-primary">
        Create
    </button>

</form> 

Views/Models/Index.cshtml
@model ModelViewModel


@section Styles {
    <style>

        .card {
            min-height: 9em;
        }

        .card:hover {
            transition: 0.5s;
            border-color: var(--primary);

        }

        .card-button {
            text-decoration: none;
            color: var(--dark);
        }

        .card-button:hover {
            text-decoration: none;
            color: var(--dark);
        }
    </style>
}
    <h1 class="display-4">Your Models</h1>
    <p>click on model to view and edit fields</p>

<div class="row my-5">

    @foreach(var item in Model.Models)
    {

    <div class="col-md-3">
        <a asp-action="Index"
           asp-controller="Fields"
           asp-route-id="@item.Id"
           class="card-button">

            <div class="card ">
                <div class="card-body">

                    <h3 class="card-title ">@item.Name</h3>

                    <p>@item.Description</p>

                </div>
            </div>
        </a>
    </div>
        
    }

<div class="col-md-3">
    <a href="#"
       data-toggle="modal" 
       data-target="#add-model-modal"
       class="card-button">

        <div class="card">

            <div class="card-body d-flex align-items-center justify-content-center">

                <span class="oi text-muted" data-glyph="plus"></span>
            </div>
        </div>
    </a>
</div>
   
</div>


<div class="modal fade" id="add-model-modal" tabindex="-1" role="dialog" aria-labelledby="add-model-modal" aria-hidden="false">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Add new Model</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-action="Add"
                  asp-controller="Models"
                  method="post">

                

                <div class="modal-body">

                    <div class="form-group">
                        <label asp-for="ModelToAdd.Name"></label>
                        <input asp-for="ModelToAdd.Name"
                               type="text"
                               class="form-control"
                               required />
                    </div>

                    <div class="form-group">
                        <label asp-for="ModelToAdd.Description"></label>
                        <textarea asp-for="ModelToAdd.Description"
                                  class="form-control"
                                  required>
                        </textarea>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-danger" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Add Model</button>
                </div>

            </form>
            
        </div>
    </div>
</div>